services:
  pytorch:
    build: .
    runtime: nvidia
    volumes:
      - pytorch_data:/workspace
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    ipc: host
    ulimits:
      memlock:
        soft: -1
        hard: -1
      stack:
        soft: 67108864
        hard: 67108864
    command: sleep infinity
    env_file:
      - .env

volumes:
  pytorch_data:
    driver: local
    driver_opts:
      type: none
      device: /home/josh/Dev/AI
      o: bind
